version: "3.8"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:15.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - ./.docker/postgres/data/:/var/lib/postgresql/data/:rw
      - ./.docker/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  app:
    container_name: app
    build: 
      context: ./
      dockerfile: ./.docker/go/Dockerfile
      target: app
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db

  news-updater:
    container_name: news-updater
    build: 
      context: ./
      dockerfile: ./.docker/go/Dockerfile
      target: news-updater
    depends_on:
      - postgres_db
      